site_name: Predicting gene expression from sequence using sparse-attention

nav:
  - Abstract & Lay Summary: 'index.md'
  - Background: 'background.md'
  - Results: 'results.md'
  - Discussion: 'discussion.md'
  - Methods: 'methods.md'
  - Conclusion & Future Work: 'conclusion.md'
  - References: 'references.md'

theme:
  name: material
  locale: en
  palette:
    scheme: default
  features:
    - navigation.instant
    - content.tabs.link

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css
